// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssl_gc_rcon_team.proto

#include "ssl_gc_rcon_team.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_ssl_5fgc_5frcon_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ssl_5fgc_5frcon_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ControllerReply;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ssl_5fgc_5frcon_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Signature;
}  // namespace protobuf_ssl_5fgc_5frcon_2eproto
class TeamRegistrationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TeamRegistration>
      _instance;
} _TeamRegistration_default_instance_;
class TeamToControllerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TeamToController>
      _instance;
  ::google::protobuf::int32 desired_keeper_;
  int advantage_choice_;
  bool substitute_bot_;
  bool ping_;
} _TeamToController_default_instance_;
class ControllerToTeamDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ControllerToTeam>
      _instance;
  const ::ControllerReply* controller_reply_;
} _ControllerToTeam_default_instance_;
namespace protobuf_ssl_5fgc_5frcon_5fteam_2eproto {
static void InitDefaultsTeamRegistration() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_TeamRegistration_default_instance_;
    new (ptr) ::TeamRegistration();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::TeamRegistration::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_TeamRegistration =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsTeamRegistration}, {
      &protobuf_ssl_5fgc_5frcon_2eproto::scc_info_Signature.base,}};

static void InitDefaultsTeamToController() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_TeamToController_default_instance_;
    new (ptr) ::TeamToController();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::TeamToController::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_TeamToController =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsTeamToController}, {
      &protobuf_ssl_5fgc_5frcon_2eproto::scc_info_Signature.base,}};

static void InitDefaultsControllerToTeam() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ControllerToTeam_default_instance_;
    new (ptr) ::ControllerToTeam();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ControllerToTeam::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ControllerToTeam =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsControllerToTeam}, {
      &protobuf_ssl_5fgc_5frcon_2eproto::scc_info_ControllerReply.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_TeamRegistration.base);
  ::google::protobuf::internal::InitSCC(&scc_info_TeamToController.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ControllerToTeam.base);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TeamRegistration, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TeamRegistration, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TeamRegistration, team_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TeamRegistration, signature_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TeamRegistration, team_),
  0,
  1,
  2,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TeamToController, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TeamToController, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TeamToController, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TeamToController, signature_),
  offsetof(::TeamToControllerDefaultTypeInternal, desired_keeper_),
  offsetof(::TeamToControllerDefaultTypeInternal, advantage_choice_),
  offsetof(::TeamToControllerDefaultTypeInternal, substitute_bot_),
  offsetof(::TeamToControllerDefaultTypeInternal, ping_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TeamToController, msg_),
  0,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ControllerToTeam, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ControllerToTeam, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ControllerToTeam, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  offsetof(::ControllerToTeamDefaultTypeInternal, controller_reply_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ControllerToTeam, msg_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::TeamRegistration)},
  { 11, 22, sizeof(::TeamToController)},
  { 27, 34, sizeof(::ControllerToTeam)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_TeamRegistration_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_TeamToController_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ControllerToTeam_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "ssl_gc_rcon_team.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026ssl_gc_rcon_team.proto\032\023ssl_gc_common."
      "proto\032\021ssl_gc_rcon.proto\"Y\n\020TeamRegistra"
      "tion\022\021\n\tteam_name\030\001 \002(\t\022\035\n\tsignature\030\002 \001"
      "(\0132\n.Signature\022\023\n\004team\030\003 \001(\0162\005.Team\"\252\001\n\020"
      "TeamToController\022\035\n\tsignature\030\001 \001(\0132\n.Si"
      "gnature\022\030\n\016desired_keeper\030\002 \001(\005H\000\022,\n\020adv"
      "antage_choice\030\003 \001(\0162\020.AdvantageChoiceH\000\022"
      "\030\n\016substitute_bot\030\004 \001(\010H\000\022\016\n\004ping\030\005 \001(\010H"
      "\000B\005\n\003msg\"M\n\020ControllerToTeam\022,\n\020controll"
      "er_reply\030\001 \001(\0132\020.ControllerReplyH\000B\005\n\003ms"
      "gJ\004\010\002\020\003*)\n\017AdvantageChoice\022\010\n\004STOP\020\000\022\014\n\010"
      "CONTINUE\020\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 450);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ssl_gc_rcon_team.proto", &protobuf_RegisterTypes);
  ::protobuf_ssl_5fgc_5fcommon_2eproto::AddDescriptors();
  ::protobuf_ssl_5fgc_5frcon_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_ssl_5fgc_5frcon_5fteam_2eproto
const ::google::protobuf::EnumDescriptor* AdvantageChoice_descriptor() {
  protobuf_ssl_5fgc_5frcon_5fteam_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_ssl_5fgc_5frcon_5fteam_2eproto::file_level_enum_descriptors[0];
}
bool AdvantageChoice_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void TeamRegistration::InitAsDefaultInstance() {
  ::_TeamRegistration_default_instance_._instance.get_mutable()->signature_ = const_cast< ::Signature*>(
      ::Signature::internal_default_instance());
}
void TeamRegistration::clear_signature() {
  if (signature_ != NULL) signature_->Clear();
  clear_has_signature();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TeamRegistration::kTeamNameFieldNumber;
const int TeamRegistration::kSignatureFieldNumber;
const int TeamRegistration::kTeamFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TeamRegistration::TeamRegistration()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ssl_5fgc_5frcon_5fteam_2eproto::scc_info_TeamRegistration.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:TeamRegistration)
}
TeamRegistration::TeamRegistration(const TeamRegistration& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  team_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_team_name()) {
    team_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.team_name_);
  }
  if (from.has_signature()) {
    signature_ = new ::Signature(*from.signature_);
  } else {
    signature_ = NULL;
  }
  team_ = from.team_;
  // @@protoc_insertion_point(copy_constructor:TeamRegistration)
}

void TeamRegistration::SharedCtor() {
  team_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&signature_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&team_) -
      reinterpret_cast<char*>(&signature_)) + sizeof(team_));
}

TeamRegistration::~TeamRegistration() {
  // @@protoc_insertion_point(destructor:TeamRegistration)
  SharedDtor();
}

void TeamRegistration::SharedDtor() {
  team_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete signature_;
}

void TeamRegistration::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* TeamRegistration::descriptor() {
  ::protobuf_ssl_5fgc_5frcon_5fteam_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5frcon_5fteam_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TeamRegistration& TeamRegistration::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ssl_5fgc_5frcon_5fteam_2eproto::scc_info_TeamRegistration.base);
  return *internal_default_instance();
}


void TeamRegistration::Clear() {
// @@protoc_insertion_point(message_clear_start:TeamRegistration)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      team_name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(signature_ != NULL);
      signature_->Clear();
    }
  }
  team_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool TeamRegistration::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:TeamRegistration)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string team_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_team_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->team_name().data(), static_cast<int>(this->team_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "TeamRegistration.team_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .Signature signature = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_signature()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .Team team = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::Team_IsValid(value)) {
            set_team(static_cast< ::Team >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                3, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:TeamRegistration)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:TeamRegistration)
  return false;
#undef DO_
}

void TeamRegistration::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:TeamRegistration)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string team_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->team_name().data(), static_cast<int>(this->team_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "TeamRegistration.team_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->team_name(), output);
  }

  // optional .Signature signature = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_signature(), output);
  }

  // optional .Team team = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->team(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:TeamRegistration)
}

::google::protobuf::uint8* TeamRegistration::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:TeamRegistration)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string team_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->team_name().data(), static_cast<int>(this->team_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "TeamRegistration.team_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->team_name(), target);
  }

  // optional .Signature signature = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_signature(), deterministic, target);
  }

  // optional .Team team = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->team(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TeamRegistration)
  return target;
}

size_t TeamRegistration::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TeamRegistration)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required string team_name = 1;
  if (has_team_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->team_name());
  }
  if (_has_bits_[0 / 32] & 6u) {
    // optional .Signature signature = 2;
    if (has_signature()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *signature_);
    }

    // optional .Team team = 3;
    if (has_team()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->team());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TeamRegistration::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TeamRegistration)
  GOOGLE_DCHECK_NE(&from, this);
  const TeamRegistration* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TeamRegistration>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TeamRegistration)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TeamRegistration)
    MergeFrom(*source);
  }
}

void TeamRegistration::MergeFrom(const TeamRegistration& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TeamRegistration)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_team_name();
      team_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.team_name_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_signature()->::Signature::MergeFrom(from.signature());
    }
    if (cached_has_bits & 0x00000004u) {
      team_ = from.team_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void TeamRegistration::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TeamRegistration)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TeamRegistration::CopyFrom(const TeamRegistration& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TeamRegistration)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TeamRegistration::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  if (has_signature()) {
    if (!this->signature_->IsInitialized()) return false;
  }
  return true;
}

void TeamRegistration::Swap(TeamRegistration* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TeamRegistration::InternalSwap(TeamRegistration* other) {
  using std::swap;
  team_name_.Swap(&other->team_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(signature_, other->signature_);
  swap(team_, other->team_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata TeamRegistration::GetMetadata() const {
  protobuf_ssl_5fgc_5frcon_5fteam_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5frcon_5fteam_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void TeamToController::InitAsDefaultInstance() {
  ::_TeamToController_default_instance_._instance.get_mutable()->signature_ = const_cast< ::Signature*>(
      ::Signature::internal_default_instance());
  ::_TeamToController_default_instance_.desired_keeper_ = 0;
  ::_TeamToController_default_instance_.advantage_choice_ = 0;
  ::_TeamToController_default_instance_.substitute_bot_ = false;
  ::_TeamToController_default_instance_.ping_ = false;
}
void TeamToController::clear_signature() {
  if (signature_ != NULL) signature_->Clear();
  clear_has_signature();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TeamToController::kSignatureFieldNumber;
const int TeamToController::kDesiredKeeperFieldNumber;
const int TeamToController::kAdvantageChoiceFieldNumber;
const int TeamToController::kSubstituteBotFieldNumber;
const int TeamToController::kPingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TeamToController::TeamToController()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ssl_5fgc_5frcon_5fteam_2eproto::scc_info_TeamToController.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:TeamToController)
}
TeamToController::TeamToController(const TeamToController& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_signature()) {
    signature_ = new ::Signature(*from.signature_);
  } else {
    signature_ = NULL;
  }
  clear_has_msg();
  switch (from.msg_case()) {
    case kDesiredKeeper: {
      set_desired_keeper(from.desired_keeper());
      break;
    }
    case kAdvantageChoice: {
      set_advantage_choice(from.advantage_choice());
      break;
    }
    case kSubstituteBot: {
      set_substitute_bot(from.substitute_bot());
      break;
    }
    case kPing: {
      set_ping(from.ping());
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:TeamToController)
}

void TeamToController::SharedCtor() {
  signature_ = NULL;
  clear_has_msg();
}

TeamToController::~TeamToController() {
  // @@protoc_insertion_point(destructor:TeamToController)
  SharedDtor();
}

void TeamToController::SharedDtor() {
  if (this != internal_default_instance()) delete signature_;
  if (has_msg()) {
    clear_msg();
  }
}

void TeamToController::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* TeamToController::descriptor() {
  ::protobuf_ssl_5fgc_5frcon_5fteam_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5frcon_5fteam_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TeamToController& TeamToController::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ssl_5fgc_5frcon_5fteam_2eproto::scc_info_TeamToController.base);
  return *internal_default_instance();
}


void TeamToController::clear_msg() {
// @@protoc_insertion_point(one_of_clear_start:TeamToController)
  switch (msg_case()) {
    case kDesiredKeeper: {
      // No need to clear
      break;
    }
    case kAdvantageChoice: {
      // No need to clear
      break;
    }
    case kSubstituteBot: {
      // No need to clear
      break;
    }
    case kPing: {
      // No need to clear
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = MSG_NOT_SET;
}


void TeamToController::Clear() {
// @@protoc_insertion_point(message_clear_start:TeamToController)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(signature_ != NULL);
    signature_->Clear();
  }
  clear_msg();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool TeamToController::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:TeamToController)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Signature signature = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_signature()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 desired_keeper = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          clear_msg();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &msg_.desired_keeper_)));
          set_has_desired_keeper();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .AdvantageChoice advantage_choice = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::AdvantageChoice_IsValid(value)) {
            set_advantage_choice(static_cast< ::AdvantageChoice >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                3, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool substitute_bot = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          clear_msg();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &msg_.substitute_bot_)));
          set_has_substitute_bot();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool ping = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          clear_msg();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &msg_.ping_)));
          set_has_ping();
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:TeamToController)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:TeamToController)
  return false;
#undef DO_
}

void TeamToController::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:TeamToController)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .Signature signature = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_signature(), output);
  }

  switch (msg_case()) {
    case kDesiredKeeper:
      ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->desired_keeper(), output);
      break;
    case kAdvantageChoice:
      ::google::protobuf::internal::WireFormatLite::WriteEnum(
        3, this->advantage_choice(), output);
      break;
    case kSubstituteBot:
      ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->substitute_bot(), output);
      break;
    case kPing:
      ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->ping(), output);
      break;
    default: ;
  }
  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:TeamToController)
}

::google::protobuf::uint8* TeamToController::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:TeamToController)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .Signature signature = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_signature(), deterministic, target);
  }

  switch (msg_case()) {
    case kDesiredKeeper:
      target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->desired_keeper(), target);
      break;
    case kAdvantageChoice:
      target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
        3, this->advantage_choice(), target);
      break;
    case kSubstituteBot:
      target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->substitute_bot(), target);
      break;
    case kPing:
      target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->ping(), target);
      break;
    default: ;
  }
  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TeamToController)
  return target;
}

size_t TeamToController::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TeamToController)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // optional .Signature signature = 1;
  if (has_signature()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *signature_);
  }

  switch (msg_case()) {
    // optional int32 desired_keeper = 2;
    case kDesiredKeeper: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->desired_keeper());
      break;
    }
    // optional .AdvantageChoice advantage_choice = 3;
    case kAdvantageChoice: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->advantage_choice());
      break;
    }
    // optional bool substitute_bot = 4;
    case kSubstituteBot: {
      total_size += 1 + 1;
      break;
    }
    // optional bool ping = 5;
    case kPing: {
      total_size += 1 + 1;
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TeamToController::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TeamToController)
  GOOGLE_DCHECK_NE(&from, this);
  const TeamToController* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TeamToController>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TeamToController)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TeamToController)
    MergeFrom(*source);
  }
}

void TeamToController::MergeFrom(const TeamToController& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TeamToController)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_signature()) {
    mutable_signature()->::Signature::MergeFrom(from.signature());
  }
  switch (from.msg_case()) {
    case kDesiredKeeper: {
      set_desired_keeper(from.desired_keeper());
      break;
    }
    case kAdvantageChoice: {
      set_advantage_choice(from.advantage_choice());
      break;
    }
    case kSubstituteBot: {
      set_substitute_bot(from.substitute_bot());
      break;
    }
    case kPing: {
      set_ping(from.ping());
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
}

void TeamToController::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TeamToController)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TeamToController::CopyFrom(const TeamToController& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TeamToController)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TeamToController::IsInitialized() const {
  if (has_signature()) {
    if (!this->signature_->IsInitialized()) return false;
  }
  return true;
}

void TeamToController::Swap(TeamToController* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TeamToController::InternalSwap(TeamToController* other) {
  using std::swap;
  swap(signature_, other->signature_);
  swap(msg_, other->msg_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata TeamToController::GetMetadata() const {
  protobuf_ssl_5fgc_5frcon_5fteam_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5frcon_5fteam_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ControllerToTeam::InitAsDefaultInstance() {
  ::_ControllerToTeam_default_instance_.controller_reply_ = const_cast< ::ControllerReply*>(
      ::ControllerReply::internal_default_instance());
}
void ControllerToTeam::set_allocated_controller_reply(::ControllerReply* controller_reply) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_msg();
  if (controller_reply) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      controller_reply = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, controller_reply, submessage_arena);
    }
    set_has_controller_reply();
    msg_.controller_reply_ = controller_reply;
  }
  // @@protoc_insertion_point(field_set_allocated:ControllerToTeam.controller_reply)
}
void ControllerToTeam::clear_controller_reply() {
  if (has_controller_reply()) {
    delete msg_.controller_reply_;
    clear_has_msg();
  }
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ControllerToTeam::kControllerReplyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ControllerToTeam::ControllerToTeam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ssl_5fgc_5frcon_5fteam_2eproto::scc_info_ControllerToTeam.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ControllerToTeam)
}
ControllerToTeam::ControllerToTeam(const ControllerToTeam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_msg();
  switch (from.msg_case()) {
    case kControllerReply: {
      mutable_controller_reply()->::ControllerReply::MergeFrom(from.controller_reply());
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:ControllerToTeam)
}

void ControllerToTeam::SharedCtor() {
  clear_has_msg();
}

ControllerToTeam::~ControllerToTeam() {
  // @@protoc_insertion_point(destructor:ControllerToTeam)
  SharedDtor();
}

void ControllerToTeam::SharedDtor() {
  if (has_msg()) {
    clear_msg();
  }
}

void ControllerToTeam::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ControllerToTeam::descriptor() {
  ::protobuf_ssl_5fgc_5frcon_5fteam_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5frcon_5fteam_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ControllerToTeam& ControllerToTeam::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ssl_5fgc_5frcon_5fteam_2eproto::scc_info_ControllerToTeam.base);
  return *internal_default_instance();
}


void ControllerToTeam::clear_msg() {
// @@protoc_insertion_point(one_of_clear_start:ControllerToTeam)
  switch (msg_case()) {
    case kControllerReply: {
      delete msg_.controller_reply_;
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = MSG_NOT_SET;
}


void ControllerToTeam::Clear() {
// @@protoc_insertion_point(message_clear_start:ControllerToTeam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_msg();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ControllerToTeam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ControllerToTeam)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .ControllerReply controller_reply = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_controller_reply()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ControllerToTeam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ControllerToTeam)
  return false;
#undef DO_
}

void ControllerToTeam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ControllerToTeam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // optional .ControllerReply controller_reply = 1;
  if (has_controller_reply()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_controller_reply(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ControllerToTeam)
}

::google::protobuf::uint8* ControllerToTeam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ControllerToTeam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // optional .ControllerReply controller_reply = 1;
  if (has_controller_reply()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_controller_reply(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ControllerToTeam)
  return target;
}

size_t ControllerToTeam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ControllerToTeam)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  switch (msg_case()) {
    // optional .ControllerReply controller_reply = 1;
    case kControllerReply: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *msg_.controller_reply_);
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ControllerToTeam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ControllerToTeam)
  GOOGLE_DCHECK_NE(&from, this);
  const ControllerToTeam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ControllerToTeam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ControllerToTeam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ControllerToTeam)
    MergeFrom(*source);
  }
}

void ControllerToTeam::MergeFrom(const ControllerToTeam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ControllerToTeam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.msg_case()) {
    case kControllerReply: {
      mutable_controller_reply()->::ControllerReply::MergeFrom(from.controller_reply());
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
}

void ControllerToTeam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ControllerToTeam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ControllerToTeam::CopyFrom(const ControllerToTeam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ControllerToTeam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ControllerToTeam::IsInitialized() const {
  return true;
}

void ControllerToTeam::Swap(ControllerToTeam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ControllerToTeam::InternalSwap(ControllerToTeam* other) {
  using std::swap;
  swap(msg_, other->msg_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ControllerToTeam::GetMetadata() const {
  protobuf_ssl_5fgc_5frcon_5fteam_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5frcon_5fteam_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::TeamRegistration* Arena::CreateMaybeMessage< ::TeamRegistration >(Arena* arena) {
  return Arena::CreateInternal< ::TeamRegistration >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::TeamToController* Arena::CreateMaybeMessage< ::TeamToController >(Arena* arena) {
  return Arena::CreateInternal< ::TeamToController >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ControllerToTeam* Arena::CreateMaybeMessage< ::ControllerToTeam >(Arena* arena) {
  return Arena::CreateInternal< ::ControllerToTeam >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
