// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssl_gc_api.proto

#include "ssl_gc_api.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_google_2fprotobuf_2fduration_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobuf_2fduration_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Duration;
}  // namespace protobuf_google_2fprotobuf_2fduration_2eproto
namespace protobuf_ssl_5fgc_5fapi_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ssl_5fgc_5fapi_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Protocol;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ssl_5fgc_5fapi_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_ProtocolEntry;
}  // namespace protobuf_ssl_5fgc_5fapi_2eproto
namespace protobuf_ssl_5fgc_5fchange_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ssl_5fgc_5fchange_2eproto ::google::protobuf::internal::SCCInfo<16> scc_info_Change;
}  // namespace protobuf_ssl_5fgc_5fchange_2eproto
namespace protobuf_ssl_5fgc_5fengine_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ssl_5fgc_5fengine_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_ContinueAction;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ssl_5fgc_5fengine_2eproto ::google::protobuf::internal::SCCInfo<5> scc_info_GcState;
}  // namespace protobuf_ssl_5fgc_5fengine_2eproto
namespace protobuf_ssl_5fgc_5fengine_5fconfig_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ssl_5fgc_5fengine_5fconfig_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_Config;
}  // namespace protobuf_ssl_5fgc_5fengine_5fconfig_2eproto
namespace protobuf_ssl_5fgc_5fstate_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ssl_5fgc_5fstate_2eproto ::google::protobuf::internal::SCCInfo<9> scc_info_State;
}  // namespace protobuf_ssl_5fgc_5fstate_2eproto
class OutputDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Output>
      _instance;
} _Output_default_instance_;
class ProtocolDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Protocol>
      _instance;
} _Protocol_default_instance_;
class ProtocolEntryDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ProtocolEntry>
      _instance;
} _ProtocolEntry_default_instance_;
class InputDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Input>
      _instance;
} _Input_default_instance_;
namespace protobuf_ssl_5fgc_5fapi_2eproto {
static void InitDefaultsOutput() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Output_default_instance_;
    new (ptr) ::Output();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Output::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<4> scc_info_Output =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 4, InitDefaultsOutput}, {
      &protobuf_ssl_5fgc_5fstate_2eproto::scc_info_State.base,
      &protobuf_ssl_5fgc_5fengine_2eproto::scc_info_GcState.base,
      &protobuf_ssl_5fgc_5fapi_2eproto::scc_info_Protocol.base,
      &protobuf_ssl_5fgc_5fengine_5fconfig_2eproto::scc_info_Config.base,}};

static void InitDefaultsProtocol() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Protocol_default_instance_;
    new (ptr) ::Protocol();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Protocol::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Protocol =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsProtocol}, {
      &protobuf_ssl_5fgc_5fapi_2eproto::scc_info_ProtocolEntry.base,}};

static void InitDefaultsProtocolEntry() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ProtocolEntry_default_instance_;
    new (ptr) ::ProtocolEntry();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ProtocolEntry::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_ProtocolEntry =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsProtocolEntry}, {
      &protobuf_ssl_5fgc_5fchange_2eproto::scc_info_Change.base,
      &protobuf_google_2fprotobuf_2fduration_2eproto::scc_info_Duration.base,}};

static void InitDefaultsInput() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Input_default_instance_;
    new (ptr) ::Input();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Input::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<3> scc_info_Input =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsInput}, {
      &protobuf_ssl_5fgc_5fchange_2eproto::scc_info_Change.base,
      &protobuf_ssl_5fgc_5fengine_5fconfig_2eproto::scc_info_Config.base,
      &protobuf_ssl_5fgc_5fengine_2eproto::scc_info_ContinueAction.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Output.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Protocol.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ProtocolEntry.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Input.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Output, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Output, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Output, match_state_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Output, gc_state_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Output, protocol_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Output, config_),
  0,
  1,
  2,
  3,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Protocol, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Protocol, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Protocol, delta_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Protocol, entry_),
  0,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtocolEntry, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtocolEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtocolEntry, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtocolEntry, change_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtocolEntry, match_time_elapsed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtocolEntry, stage_time_elapsed_),
  3,
  0,
  1,
  2,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Input, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Input, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Input, change_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Input, reset_match_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Input, config_delta_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Input, continue_action_),
  0,
  3,
  1,
  2,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, sizeof(::Output)},
  { 13, 20, sizeof(::Protocol)},
  { 22, 31, sizeof(::ProtocolEntry)},
  { 35, 44, sizeof(::Input)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Output_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Protocol_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ProtocolEntry_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Input_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "ssl_gc_api.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020ssl_gc_api.proto\032\022ssl_gc_state.proto\032\023"
      "ssl_gc_change.proto\032\023ssl_gc_engine.proto"
      "\032\032ssl_gc_engine_config.proto\032\036google/pro"
      "tobuf/duration.proto\"w\n\006Output\022\033\n\013match_"
      "state\030\001 \001(\0132\006.State\022\032\n\010gc_state\030\002 \001(\0132\010."
      "GcState\022\033\n\010protocol\030\003 \001(\0132\t.Protocol\022\027\n\006"
      "config\030\004 \001(\0132\007.Config\"8\n\010Protocol\022\r\n\005del"
      "ta\030\001 \001(\010\022\035\n\005entry\030\002 \003(\0132\016.ProtocolEntry\""
      "\242\001\n\rProtocolEntry\022\n\n\002id\030\001 \001(\005\022\027\n\006change\030"
      "\002 \001(\0132\007.Change\0225\n\022match_time_elapsed\030\003 \001"
      "(\0132\031.google.protobuf.Duration\0225\n\022stage_t"
      "ime_elapsed\030\004 \001(\0132\031.google.protobuf.Dura"
      "tion\"~\n\005Input\022\027\n\006change\030\001 \001(\0132\007.Change\022\023"
      "\n\013reset_match\030\002 \001(\010\022\035\n\014config_delta\030\003 \001("
      "\0132\007.Config\022(\n\017continue_action\030\004 \001(\0132\017.Co"
      "ntinueAction"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 612);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ssl_gc_api.proto", &protobuf_RegisterTypes);
  ::protobuf_ssl_5fgc_5fstate_2eproto::AddDescriptors();
  ::protobuf_ssl_5fgc_5fchange_2eproto::AddDescriptors();
  ::protobuf_ssl_5fgc_5fengine_2eproto::AddDescriptors();
  ::protobuf_ssl_5fgc_5fengine_5fconfig_2eproto::AddDescriptors();
  ::protobuf_google_2fprotobuf_2fduration_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_ssl_5fgc_5fapi_2eproto

// ===================================================================

void Output::InitAsDefaultInstance() {
  ::_Output_default_instance_._instance.get_mutable()->match_state_ = const_cast< ::State*>(
      ::State::internal_default_instance());
  ::_Output_default_instance_._instance.get_mutable()->gc_state_ = const_cast< ::GcState*>(
      ::GcState::internal_default_instance());
  ::_Output_default_instance_._instance.get_mutable()->protocol_ = const_cast< ::Protocol*>(
      ::Protocol::internal_default_instance());
  ::_Output_default_instance_._instance.get_mutable()->config_ = const_cast< ::Config*>(
      ::Config::internal_default_instance());
}
void Output::clear_match_state() {
  if (match_state_ != NULL) match_state_->Clear();
  clear_has_match_state();
}
void Output::clear_gc_state() {
  if (gc_state_ != NULL) gc_state_->Clear();
  clear_has_gc_state();
}
void Output::clear_config() {
  if (config_ != NULL) config_->Clear();
  clear_has_config();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Output::kMatchStateFieldNumber;
const int Output::kGcStateFieldNumber;
const int Output::kProtocolFieldNumber;
const int Output::kConfigFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Output::Output()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ssl_5fgc_5fapi_2eproto::scc_info_Output.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Output)
}
Output::Output(const Output& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_match_state()) {
    match_state_ = new ::State(*from.match_state_);
  } else {
    match_state_ = NULL;
  }
  if (from.has_gc_state()) {
    gc_state_ = new ::GcState(*from.gc_state_);
  } else {
    gc_state_ = NULL;
  }
  if (from.has_protocol()) {
    protocol_ = new ::Protocol(*from.protocol_);
  } else {
    protocol_ = NULL;
  }
  if (from.has_config()) {
    config_ = new ::Config(*from.config_);
  } else {
    config_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:Output)
}

void Output::SharedCtor() {
  ::memset(&match_state_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&config_) -
      reinterpret_cast<char*>(&match_state_)) + sizeof(config_));
}

Output::~Output() {
  // @@protoc_insertion_point(destructor:Output)
  SharedDtor();
}

void Output::SharedDtor() {
  if (this != internal_default_instance()) delete match_state_;
  if (this != internal_default_instance()) delete gc_state_;
  if (this != internal_default_instance()) delete protocol_;
  if (this != internal_default_instance()) delete config_;
}

void Output::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Output::descriptor() {
  ::protobuf_ssl_5fgc_5fapi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5fapi_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Output& Output::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ssl_5fgc_5fapi_2eproto::scc_info_Output.base);
  return *internal_default_instance();
}


void Output::Clear() {
// @@protoc_insertion_point(message_clear_start:Output)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(match_state_ != NULL);
      match_state_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(gc_state_ != NULL);
      gc_state_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(protocol_ != NULL);
      protocol_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(config_ != NULL);
      config_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Output::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Output)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .State match_state = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_match_state()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .GcState gc_state = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_gc_state()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .Protocol protocol = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_protocol()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .Config config = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_config()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Output)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Output)
  return false;
#undef DO_
}

void Output::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Output)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .State match_state = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_match_state(), output);
  }

  // optional .GcState gc_state = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_gc_state(), output);
  }

  // optional .Protocol protocol = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_protocol(), output);
  }

  // optional .Config config = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_config(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Output)
}

::google::protobuf::uint8* Output::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Output)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .State match_state = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_match_state(), deterministic, target);
  }

  // optional .GcState gc_state = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_gc_state(), deterministic, target);
  }

  // optional .Protocol protocol = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_protocol(), deterministic, target);
  }

  // optional .Config config = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_config(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Output)
  return target;
}

size_t Output::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Output)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 15u) {
    // optional .State match_state = 1;
    if (has_match_state()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *match_state_);
    }

    // optional .GcState gc_state = 2;
    if (has_gc_state()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *gc_state_);
    }

    // optional .Protocol protocol = 3;
    if (has_protocol()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *protocol_);
    }

    // optional .Config config = 4;
    if (has_config()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *config_);
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Output::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Output)
  GOOGLE_DCHECK_NE(&from, this);
  const Output* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Output>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Output)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Output)
    MergeFrom(*source);
  }
}

void Output::MergeFrom(const Output& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Output)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_match_state()->::State::MergeFrom(from.match_state());
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_gc_state()->::GcState::MergeFrom(from.gc_state());
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_protocol()->::Protocol::MergeFrom(from.protocol());
    }
    if (cached_has_bits & 0x00000008u) {
      mutable_config()->::Config::MergeFrom(from.config());
    }
  }
}

void Output::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Output)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Output::CopyFrom(const Output& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Output)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Output::IsInitialized() const {
  if (has_match_state()) {
    if (!this->match_state_->IsInitialized()) return false;
  }
  if (has_gc_state()) {
    if (!this->gc_state_->IsInitialized()) return false;
  }
  if (has_protocol()) {
    if (!this->protocol_->IsInitialized()) return false;
  }
  return true;
}

void Output::Swap(Output* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Output::InternalSwap(Output* other) {
  using std::swap;
  swap(match_state_, other->match_state_);
  swap(gc_state_, other->gc_state_);
  swap(protocol_, other->protocol_);
  swap(config_, other->config_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Output::GetMetadata() const {
  protobuf_ssl_5fgc_5fapi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5fapi_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Protocol::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Protocol::kDeltaFieldNumber;
const int Protocol::kEntryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Protocol::Protocol()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ssl_5fgc_5fapi_2eproto::scc_info_Protocol.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Protocol)
}
Protocol::Protocol(const Protocol& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      entry_(from.entry_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  delta_ = from.delta_;
  // @@protoc_insertion_point(copy_constructor:Protocol)
}

void Protocol::SharedCtor() {
  delta_ = false;
}

Protocol::~Protocol() {
  // @@protoc_insertion_point(destructor:Protocol)
  SharedDtor();
}

void Protocol::SharedDtor() {
}

void Protocol::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Protocol::descriptor() {
  ::protobuf_ssl_5fgc_5fapi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5fapi_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Protocol& Protocol::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ssl_5fgc_5fapi_2eproto::scc_info_Protocol.base);
  return *internal_default_instance();
}


void Protocol::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  entry_.Clear();
  delta_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Protocol::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Protocol)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool delta = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_delta();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &delta_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .ProtocolEntry entry = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_entry()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Protocol)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Protocol)
  return false;
#undef DO_
}

void Protocol::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Protocol)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool delta = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->delta(), output);
  }

  // repeated .ProtocolEntry entry = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->entry_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->entry(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Protocol)
}

::google::protobuf::uint8* Protocol::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Protocol)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool delta = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->delta(), target);
  }

  // repeated .ProtocolEntry entry = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->entry_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->entry(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol)
  return target;
}

size_t Protocol::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .ProtocolEntry entry = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->entry_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->entry(static_cast<int>(i)));
    }
  }

  // optional bool delta = 1;
  if (has_delta()) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Protocol::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Protocol)
  GOOGLE_DCHECK_NE(&from, this);
  const Protocol* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Protocol>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Protocol)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Protocol)
    MergeFrom(*source);
  }
}

void Protocol::MergeFrom(const Protocol& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Protocol)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  entry_.MergeFrom(from.entry_);
  if (from.has_delta()) {
    set_delta(from.delta());
  }
}

void Protocol::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Protocol)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Protocol::CopyFrom(const Protocol& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Protocol::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->entry())) return false;
  return true;
}

void Protocol::Swap(Protocol* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Protocol::InternalSwap(Protocol* other) {
  using std::swap;
  CastToBase(&entry_)->InternalSwap(CastToBase(&other->entry_));
  swap(delta_, other->delta_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Protocol::GetMetadata() const {
  protobuf_ssl_5fgc_5fapi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5fapi_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ProtocolEntry::InitAsDefaultInstance() {
  ::_ProtocolEntry_default_instance_._instance.get_mutable()->change_ = const_cast< ::Change*>(
      ::Change::internal_default_instance());
  ::_ProtocolEntry_default_instance_._instance.get_mutable()->match_time_elapsed_ = const_cast< ::google::protobuf::Duration*>(
      ::google::protobuf::Duration::internal_default_instance());
  ::_ProtocolEntry_default_instance_._instance.get_mutable()->stage_time_elapsed_ = const_cast< ::google::protobuf::Duration*>(
      ::google::protobuf::Duration::internal_default_instance());
}
void ProtocolEntry::clear_change() {
  if (change_ != NULL) change_->Clear();
  clear_has_change();
}
void ProtocolEntry::clear_match_time_elapsed() {
  if (match_time_elapsed_ != NULL) match_time_elapsed_->Clear();
  clear_has_match_time_elapsed();
}
void ProtocolEntry::clear_stage_time_elapsed() {
  if (stage_time_elapsed_ != NULL) stage_time_elapsed_->Clear();
  clear_has_stage_time_elapsed();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProtocolEntry::kIdFieldNumber;
const int ProtocolEntry::kChangeFieldNumber;
const int ProtocolEntry::kMatchTimeElapsedFieldNumber;
const int ProtocolEntry::kStageTimeElapsedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProtocolEntry::ProtocolEntry()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ssl_5fgc_5fapi_2eproto::scc_info_ProtocolEntry.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ProtocolEntry)
}
ProtocolEntry::ProtocolEntry(const ProtocolEntry& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_change()) {
    change_ = new ::Change(*from.change_);
  } else {
    change_ = NULL;
  }
  if (from.has_match_time_elapsed()) {
    match_time_elapsed_ = new ::google::protobuf::Duration(*from.match_time_elapsed_);
  } else {
    match_time_elapsed_ = NULL;
  }
  if (from.has_stage_time_elapsed()) {
    stage_time_elapsed_ = new ::google::protobuf::Duration(*from.stage_time_elapsed_);
  } else {
    stage_time_elapsed_ = NULL;
  }
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:ProtocolEntry)
}

void ProtocolEntry::SharedCtor() {
  ::memset(&change_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&change_)) + sizeof(id_));
}

ProtocolEntry::~ProtocolEntry() {
  // @@protoc_insertion_point(destructor:ProtocolEntry)
  SharedDtor();
}

void ProtocolEntry::SharedDtor() {
  if (this != internal_default_instance()) delete change_;
  if (this != internal_default_instance()) delete match_time_elapsed_;
  if (this != internal_default_instance()) delete stage_time_elapsed_;
}

void ProtocolEntry::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ProtocolEntry::descriptor() {
  ::protobuf_ssl_5fgc_5fapi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5fapi_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ProtocolEntry& ProtocolEntry::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ssl_5fgc_5fapi_2eproto::scc_info_ProtocolEntry.base);
  return *internal_default_instance();
}


void ProtocolEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtocolEntry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(change_ != NULL);
      change_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(match_time_elapsed_ != NULL);
      match_time_elapsed_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(stage_time_elapsed_ != NULL);
      stage_time_elapsed_->Clear();
    }
  }
  id_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ProtocolEntry::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ProtocolEntry)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .Change change = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_change()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .google.protobuf.Duration match_time_elapsed = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_match_time_elapsed()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .google.protobuf.Duration stage_time_elapsed = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_stage_time_elapsed()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ProtocolEntry)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ProtocolEntry)
  return false;
#undef DO_
}

void ProtocolEntry::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ProtocolEntry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 id = 1;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // optional .Change change = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_change(), output);
  }

  // optional .google.protobuf.Duration match_time_elapsed = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_match_time_elapsed(), output);
  }

  // optional .google.protobuf.Duration stage_time_elapsed = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_stage_time_elapsed(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ProtocolEntry)
}

::google::protobuf::uint8* ProtocolEntry::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ProtocolEntry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 id = 1;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // optional .Change change = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_change(), deterministic, target);
  }

  // optional .google.protobuf.Duration match_time_elapsed = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_match_time_elapsed(), deterministic, target);
  }

  // optional .google.protobuf.Duration stage_time_elapsed = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_stage_time_elapsed(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtocolEntry)
  return target;
}

size_t ProtocolEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtocolEntry)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 15u) {
    // optional .Change change = 2;
    if (has_change()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *change_);
    }

    // optional .google.protobuf.Duration match_time_elapsed = 3;
    if (has_match_time_elapsed()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *match_time_elapsed_);
    }

    // optional .google.protobuf.Duration stage_time_elapsed = 4;
    if (has_stage_time_elapsed()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *stage_time_elapsed_);
    }

    // optional int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ProtocolEntry::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ProtocolEntry)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtocolEntry* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ProtocolEntry>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ProtocolEntry)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ProtocolEntry)
    MergeFrom(*source);
  }
}

void ProtocolEntry::MergeFrom(const ProtocolEntry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtocolEntry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_change()->::Change::MergeFrom(from.change());
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_match_time_elapsed()->::google::protobuf::Duration::MergeFrom(from.match_time_elapsed());
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_stage_time_elapsed()->::google::protobuf::Duration::MergeFrom(from.stage_time_elapsed());
    }
    if (cached_has_bits & 0x00000008u) {
      id_ = from.id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ProtocolEntry::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ProtocolEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtocolEntry::CopyFrom(const ProtocolEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtocolEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtocolEntry::IsInitialized() const {
  if (has_change()) {
    if (!this->change_->IsInitialized()) return false;
  }
  return true;
}

void ProtocolEntry::Swap(ProtocolEntry* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProtocolEntry::InternalSwap(ProtocolEntry* other) {
  using std::swap;
  swap(change_, other->change_);
  swap(match_time_elapsed_, other->match_time_elapsed_);
  swap(stage_time_elapsed_, other->stage_time_elapsed_);
  swap(id_, other->id_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ProtocolEntry::GetMetadata() const {
  protobuf_ssl_5fgc_5fapi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5fapi_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Input::InitAsDefaultInstance() {
  ::_Input_default_instance_._instance.get_mutable()->change_ = const_cast< ::Change*>(
      ::Change::internal_default_instance());
  ::_Input_default_instance_._instance.get_mutable()->config_delta_ = const_cast< ::Config*>(
      ::Config::internal_default_instance());
  ::_Input_default_instance_._instance.get_mutable()->continue_action_ = const_cast< ::ContinueAction*>(
      ::ContinueAction::internal_default_instance());
}
void Input::clear_change() {
  if (change_ != NULL) change_->Clear();
  clear_has_change();
}
void Input::clear_config_delta() {
  if (config_delta_ != NULL) config_delta_->Clear();
  clear_has_config_delta();
}
void Input::clear_continue_action() {
  if (continue_action_ != NULL) continue_action_->Clear();
  clear_has_continue_action();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Input::kChangeFieldNumber;
const int Input::kResetMatchFieldNumber;
const int Input::kConfigDeltaFieldNumber;
const int Input::kContinueActionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Input::Input()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ssl_5fgc_5fapi_2eproto::scc_info_Input.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Input)
}
Input::Input(const Input& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_change()) {
    change_ = new ::Change(*from.change_);
  } else {
    change_ = NULL;
  }
  if (from.has_config_delta()) {
    config_delta_ = new ::Config(*from.config_delta_);
  } else {
    config_delta_ = NULL;
  }
  if (from.has_continue_action()) {
    continue_action_ = new ::ContinueAction(*from.continue_action_);
  } else {
    continue_action_ = NULL;
  }
  reset_match_ = from.reset_match_;
  // @@protoc_insertion_point(copy_constructor:Input)
}

void Input::SharedCtor() {
  ::memset(&change_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&reset_match_) -
      reinterpret_cast<char*>(&change_)) + sizeof(reset_match_));
}

Input::~Input() {
  // @@protoc_insertion_point(destructor:Input)
  SharedDtor();
}

void Input::SharedDtor() {
  if (this != internal_default_instance()) delete change_;
  if (this != internal_default_instance()) delete config_delta_;
  if (this != internal_default_instance()) delete continue_action_;
}

void Input::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Input::descriptor() {
  ::protobuf_ssl_5fgc_5fapi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5fapi_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Input& Input::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ssl_5fgc_5fapi_2eproto::scc_info_Input.base);
  return *internal_default_instance();
}


void Input::Clear() {
// @@protoc_insertion_point(message_clear_start:Input)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(change_ != NULL);
      change_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(config_delta_ != NULL);
      config_delta_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(continue_action_ != NULL);
      continue_action_->Clear();
    }
  }
  reset_match_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Input::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Input)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Change change = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_change()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool reset_match = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_reset_match();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &reset_match_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .Config config_delta = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_config_delta()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .ContinueAction continue_action = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_continue_action()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Input)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Input)
  return false;
#undef DO_
}

void Input::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Input)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .Change change = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_change(), output);
  }

  // optional bool reset_match = 2;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->reset_match(), output);
  }

  // optional .Config config_delta = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_config_delta(), output);
  }

  // optional .ContinueAction continue_action = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_continue_action(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Input)
}

::google::protobuf::uint8* Input::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Input)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .Change change = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_change(), deterministic, target);
  }

  // optional bool reset_match = 2;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->reset_match(), target);
  }

  // optional .Config config_delta = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_config_delta(), deterministic, target);
  }

  // optional .ContinueAction continue_action = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_continue_action(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Input)
  return target;
}

size_t Input::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Input)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 15u) {
    // optional .Change change = 1;
    if (has_change()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *change_);
    }

    // optional .Config config_delta = 3;
    if (has_config_delta()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *config_delta_);
    }

    // optional .ContinueAction continue_action = 4;
    if (has_continue_action()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *continue_action_);
    }

    // optional bool reset_match = 2;
    if (has_reset_match()) {
      total_size += 1 + 1;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Input::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Input)
  GOOGLE_DCHECK_NE(&from, this);
  const Input* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Input>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Input)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Input)
    MergeFrom(*source);
  }
}

void Input::MergeFrom(const Input& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Input)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_change()->::Change::MergeFrom(from.change());
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_config_delta()->::Config::MergeFrom(from.config_delta());
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_continue_action()->::ContinueAction::MergeFrom(from.continue_action());
    }
    if (cached_has_bits & 0x00000008u) {
      reset_match_ = from.reset_match_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Input::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Input)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Input::CopyFrom(const Input& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Input)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Input::IsInitialized() const {
  if (has_change()) {
    if (!this->change_->IsInitialized()) return false;
  }
  if (has_continue_action()) {
    if (!this->continue_action_->IsInitialized()) return false;
  }
  return true;
}

void Input::Swap(Input* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Input::InternalSwap(Input* other) {
  using std::swap;
  swap(change_, other->change_);
  swap(config_delta_, other->config_delta_);
  swap(continue_action_, other->continue_action_);
  swap(reset_match_, other->reset_match_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Input::GetMetadata() const {
  protobuf_ssl_5fgc_5fapi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssl_5fgc_5fapi_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Output* Arena::CreateMaybeMessage< ::Output >(Arena* arena) {
  return Arena::CreateInternal< ::Output >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Protocol* Arena::CreateMaybeMessage< ::Protocol >(Arena* arena) {
  return Arena::CreateInternal< ::Protocol >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ProtocolEntry* Arena::CreateMaybeMessage< ::ProtocolEntry >(Arena* arena) {
  return Arena::CreateInternal< ::ProtocolEntry >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Input* Arena::CreateMaybeMessage< ::Input >(Arena* arena) {
  return Arena::CreateInternal< ::Input >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
